version: "3.8"

services:
    db:
        image: mysql:8.0
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: trustno1
            MYSQL_DATABASE: sample_db
            MYSQL_USER: lightbox
            MYSQL_PASSWORD: trustno1
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: trustno1
        ports:
            - "8080:80"
        depends_on:
            - db

volumes:
    db_data:
